<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>org.dromara</groupId>
        <artifactId>seewis-cloud-ultra</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <modules>
        <module>seewis-api-bom</module>
        <module>seewis-api-system</module>
        <module>seewis-api-resource</module>
        <module>seewis-api-workflow</module>
    </modules>

    <artifactId>seewis-api</artifactId>
    <packaging>pom</packaging>

    <description>
        seewis-api系统接口
    </description>

</project>
